# Generated by Django 3.1 on 2020-08-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='author',
            field=models.CharField(default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='recorder',
            name='backup_info',
            field=models.CharField(default='none', max_length=128),
        ),
        migrations.AddField(
            model_name='recorder',
            name='ip',
            field=models.GenericIPAddressField(default='none'),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='title',
            field=models.CharField(default='Unnamed Title', max_length=64),
        ),
    ]
