# Generated by Django 2.2 on 2020-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0002_auto_20200822_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorder',
            name='password',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='recorder',
            name='is_bold',
            field=models.BooleanField(default=False),
        ),
    ]
