# Generated by Django 2.2 on 2020-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0003_auto_20200829_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRadar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='0', max_length=20)),
                ('path', models.CharField(default='none', max_length=256)),
                ('upload_date', models.DateTimeField(verbose_name='upload date')),
                ('download_times', models.IntegerField(default=0)),
                ('author', models.CharField(default='Unknown', max_length=32)),
                ('ip', models.GenericIPAddressField(default='none')),
                ('backup_info', models.CharField(default='none', max_length=128)),
            ],
        ),
    ]
