# Generated by Django 2.2 on 2020-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0004_fileradar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileradar',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
