# Generated by Django 2.2 on 2020-09-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0005_fileradar_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileradar',
            name='file_type',
            field=models.CharField(default='none', max_length=6),
        ),
    ]
