# Generated by Django 2.2 on 2020-09-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0006_fileradar_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileradar',
            name='backup_info',
        ),
        migrations.AddField(
            model_name='fileradar',
            name='file_name',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
