# Generated by Django 2.2 on 2020-09-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0007_auto_20200908_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileradar',
            name='size',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
