# Generated by Django 2.2 on 2020-09-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenscall', '0008_auto_20200908_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileradar',
            name='crc',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
