# Generated by Django 2.2 on 2020-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong',
            field=models.IntegerField(default=0),
        ),
    ]
